fix ArgumentException thrown in IrcClient._Event_JOIN() with channel syncing
If the active channel syncing feature is enabled then an ArgumentException
might be thrown in IrcClient._Event_JOIN() if we are already joined to that
channel. Usually this should never happen but there are 2 independent reports
of running into the said ArgumentException with the following stack trace:

    System.ArgumentException: Item has already been added. Key in dictionary: '#channel'  Key being added: '#channel'
       at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
       at System.Collections.Hashtable.SyncHashtable.Add(Object key, Object value)
       at Meebey.SmartIrc4net.IrcClient._Event_JOIN(IrcMessageData ircdata) in c:\Users\User\Documents\Visual Studio 2013\remoteLibrary\SmartIrc4net\src\IrcClient\IrcClient.cs:line 2171
       at Meebey.SmartIrc4net.IrcClient._HandleEvents(IrcMessageData ircdata) in c:\Users\User\Documents\Visual Studio 2013\remoteLibrary\SmartIrc4net\src\IrcClient\IrcClient.cs:line 1471
       at Meebey.SmartIrc4net.IrcClient._Worker(Object sender, ReadLineEventArgs e) in c:\Users\User\Documents\Visual Studio 2013\remoteLibrary\SmartIrc4net\src\IrcClient\IrcClient.cs:line 1169
       at Meebey.SmartIrc4net.ReadLineEventHandler.Invoke(Object sender, ReadLineEventArgs e)
       at Meebey.SmartIrc4net.IrcConnection.ReadLine(Boolean blocking) in c:\Users\User\Documents\Visual Studio 2013\remoteLibrary\SmartIrc4net\src\IrcConnection\IrcConnection.cs:line 902
       at Meebey.SmartIrc4net.IrcConnection.Listen(Boolean blocking) in c:\Users\User\Documents\Visual Studio 2013\remoteLibrary\SmartIrc4net\src\IrcConnection\IrcConnection.cs:line 841
       at Meebey.SmartIrc4net.IrcConnection.Listen() in c:\Users\User\Documents\Visual Studio 2013\remoteLibrary\SmartIrc4net\src\IrcConnection\IrcConnection.cs:line 855

To fix this issue we are now checking if the channel already exists. (closes: GH-19)